export const servicesData = [
  {
    "id": 1,
    "name": "Cook",
    "description": "Professional chefs for your events",
    "icon": "LuChefHat",
    "image": "https://static.vecteezy.com/system/resources/previews/005/380/467/non_2x/professional-chef-female-cooking-concept-character-vector.jpg",
    "priceRange": "₹200/hr - ₹500/hr",
    "rating": 4.5,
    "reviewsCount": 120,
    "serviceDuration": "2 hours minimum",
    "availability": "Available Now",
    "tags": ["wedding", "private event", "catering"],
    "aboutService": "Hire professional chefs with 5+ years of experience for your private events, parties, and catering needs."
  },
  {
    "id": 2,
    "name": "Plumber",
    "description": "Expert plumbing solutions for homes and offices",
    "icon": "FaTools",
    "image": "https://static.vecteezy.com/system/resources/previews/018/807/803/non_2x/plumber-repairman-cartoon-illustration-vector.jpg",
    "priceRange": "₹300/hr - ₹700/hr",
    "rating": 4.2,
    "reviewsCount": 95,
    "serviceDuration": "1 hour minimum",
    "availability": "Available Now",
    "tags": ["leakage", "pipe fitting", "bathroom"],
    "aboutService": "Licensed plumbers offering 24/7 service for leak repairs, installations, and general maintenance."
  },
  {
    "id": 3,
    "name": "Driver",
    "description": "Professional drivers for daily or event needs",
    "icon": "RiSteering2Line",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1wBXs2bw9f2039yXQQOYR6wHfmNp9DCMXbTxGMWsItLm_BXP5QXZjmcZ89Wys9ZyNUrc&usqp=CAU",
    "priceRange": "₹500/day - ₹1200/day",
    "rating": 4.6,
    "reviewsCount": 150,
    "serviceDuration": "Half day / Full day",
    "availability": "Available Now",
    "tags": ["personal driver", "event driver", "office commute"],
    "aboutService": "Experienced and verified drivers for personal and professional travel, available for short and long term."
  },
  {
    "id": 4,
    "name": "Home Doctor",
    "description": "Consultations and treatments at your doorstep",
    "icon": "FaUserMd",
    "image": "https://thumbs.dreamstime.com/b/doctor-attending-patient-home-flat-illustration-practitioner-white-coat-stethoscope-sick-schoolboy-poster-abstract-69614315.jpg",
    "priceRange": "₹800/visit - ₹2000/visit",
    "rating": 4.8,
    "reviewsCount": 80,
    "serviceDuration": "Per Visit",
    "availability": "On Request",
    "tags": ["home visit", "doctor", "healthcare"],
    "aboutService": "Certified doctors providing home consultation for general illnesses, minor injuries, and health checkups."
  },
  {
    "id": 5,
    "name": "Electrician",
    "description": "Professional electricians for all types of works",
    "icon": "MdElectricalServices",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkvkVUso66_HU472z6xopSa39QkrLHX7gbWRXa4F0Fc33QYohhGwAyC5PXBG89xACbHds&usqp=CAU",
    "priceRange": "₹250/hr - ₹600/hr",
    "rating": 4.4,
    "reviewsCount": 70,
    "serviceDuration": "1 hour minimum",
    "availability": "Available Now",
    "tags": ["wiring", "lighting", "repairs"],
    "aboutService": "Certified electricians for wiring, fixing appliances, fitting new lights and more. Reliable and safe services."
  },
  {
    "id": 6,
    "name": "Home Worker",
    "description": "Housekeeping and domestic help",
    "icon": "GiHouseKeys",
    "image": "https://static.vecteezy.com/system/resources/previews/046/452/751/non_2x/trendy-flat-illustration-of-domestic-worker-vector.jpg",
    "priceRange": "₹300/day - ₹800/day",
    "rating": 4.1,
    "reviewsCount": 50,
    "serviceDuration": "Per Day",
    "availability": "Available Now",
    "tags": ["cleaning", "dusting", "laundry"],
    "aboutService": "Trained workers to assist with cleaning, cooking, dusting and daily household chores efficiently."
  },
  {
    "id": 7,
    "name": "Maid",
    "description": "General help for moving and shifting",
    "icon": "FaHandHoldingHeart",
    "image": "https://cdn3.vectorstock.com/i/1000x1000/43/32/young-woman-in-wheelchair-with-male-helper-vector-24934332.jpg",
    "priceRange": "₹200/hr - ₹500/hr",
    "rating": 4.3,
    "reviewsCount": 65,
    "serviceDuration": "2 hours minimum",
    "availability": "Available Now",
    "tags": ["moving", "lifting", "packing"],
    "aboutService": "Helpers for small shifting, lifting heavy items, packing services, and logistics support within city limits."
  },
  {
    "id": 8,
    "name": "Security Guard",
    "description": "Trained guards for residential and commercial security",
    "icon": "GiBodyArmor",
    "image": "https://static.vecteezy.com/system/resources/previews/007/469/006/non_2x/colorful-simple-flat-of-security-guard-icon-or-symbol-people-concept-illustration-vector.jpg",
    "priceRange": "₹8000/month - ₹15000/month",
    "rating": 4.7,
    "reviewsCount": 90,
    "serviceDuration": "Monthly",
    "availability": "On Request",
    "tags": ["security", "guard", "safety"],
    "aboutService": "Professionally trained guards with background verification, available for homes, apartments and offices."
  },
  {
    "id": 9,
    "name": "Private Tutor",
    "description": "Home tutoring services for students",
    "icon": "FaChalkboardTeacher",
    "image": "https://images.unsplash.com/photo-1596495577886-d920f1fb7238",
    "priceRange": "₹400/hr - ₹800/hr",
    "rating": 4.6,
    "reviewsCount": 110,
    "serviceDuration": "1 hour minimum",
    "availability": "Available Now",
    "tags": ["maths", "science", "english"],
    "aboutService": "Certified tutors available for school subjects and competitive exams. Focused on individual attention."
  },
  {
    "id": 10,
    "name": "Gardener",
    "description": "Professional gardening and lawn maintenance",
    "icon": "GiPlantWatering",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUX8poWbhOZnn7gArSwtM0IJTMU0gSviEQng&s",
    "priceRange": "₹300/hr - ₹700/hr",
    "rating": 4.3,
    "reviewsCount": 45,
    "serviceDuration": "Per Visit",
    "availability": "Available Now",
    "tags": ["garden", "plants", "maintenance"],
    "aboutService": "Experienced gardeners available for landscaping, lawn maintenance, and plant care on a one-time or regular basis."
  }
]
